// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
public class LoginSuiteTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void loginSuite() {
    driver.get("http://192.168.168.98:8080/OceanviewWEB/ShowLogin.action?loginFail=true");
    driver.manage().window().setSize(new Dimension(1050, 708));
    driver.findElement(By.id("Login_username")).sendKeys("stonewain.support");
    driver.findElement(By.id("Login_password")).sendKeys("pearplanet");
    driver.findElement(By.id("Login_button")).click();
    try {
      Thread.sleep(12000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    driver.findElement(By.id("ocv_Nav-Trading-Label")).click();
    driver.findElement(By.id("ocv_Nav-Trading-Menu-LoanEntry-Label")).click();
    try {
      Thread.sleep(16000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    driver.switchTo().frame(1);
    driver.findElement(By.cssSelector("#LoanEntryGrid-SearchForm-counterparty .o3-field-autocomplete-dropdownarrow")).click();
    driver.findElement(By.id("yui_3_13_0_1_1562152392723_2435")).click();
    {
      WebElement element = driver.findElement(By.id("o3-CommonAutoComplete"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector(".o3-formgrid-col-securityId .o3-field-inputcontainer")).click();
    driver.findElement(By.cssSelector(".o3-formgrid-col-securityId .o3-field-inputcontainer")).sendKeys("ibm");
    driver.findElement(By.id("yui_3_13_0_1_1562161581691_2748")).click();
  }
}
